name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-ci.txt ]; then
            pip install -r requirements-ci.txt
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements file"
          fi
      - name: Run tests (if present)
        run: |
          if [ -d tests ] || ls -1 *.py 2>/dev/null | grep -q test_; then
            pip install pytest >/dev/null 2>&1 || true
            pytest -q || echo "Tests failed (non-blocking)"
          else
            echo "No tests directory"
          fi
      - name: Run demo (if script exists)
        run: |
          if [ -f scripts/run_demo.py ]; then
            python scripts/run_demo.py --out demo_report_ci.json --html-out demo_report_ci.html --pretty || echo 'Demo script failed'
          else
            echo 'No demo script'
          fi
      - name: Upload demo report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: demo-report
          path: |
            demo_report_ci.json
            demo_report_ci.html
